const $=id=>document.getElementById(id);
const hashParams=new URLSearchParams(location.hash.startsWith('#')?location.hash.slice(1):'');
const handoffToken=hashParams.get('auth')||'';
if(handoffToken){localStorage.setItem('ads_admin_token',handoffToken);sessionStorage.setItem('ads_admin_token',handoffToken);history.replaceState(null,'',location.pathname+location.search);}
let token=handoffToken||localStorage.getItem('ads_admin_token')||sessionStorage.getItem('ads_admin_token')||'';
let selectedKey='',selectedTaskId='',activeTaskId='task1',students=[],tasks=[],pendingRoster=[];
let lastMessageSignature='';
const imageUrls=new Set();
function fmtTime(iso){if(!iso)return'—';try{return new Date(iso).toLocaleString('zh-CN',{hour12:false});}catch{return iso;}}
function err(text=''){$('adminError').textContent=text;$('adminError').classList.toggle('hidden',!text);}
function rosterErr(text=''){$('rosterError').textContent=text;$('rosterError').classList.toggle('hidden',!text);}
async function api(path,opts={}){const headers=new Headers(opts.headers||{});if(token)headers.set('Authorization',`Bearer ${token}`);const res=await fetch(path,{...opts,headers});if(res.status===401){token='';sessionStorage.removeItem('ads_admin_token');localStorage.removeItem('ads_admin_token');showLogin();throw new Error('登录已失效，请重新登录');}return res;}
function showLogin(){$('dashboard').classList.add('hidden');$('adminLogin').classList.remove('hidden');}
function showDash(){$('adminLogin').classList.add('hidden');$('dashboard').classList.remove('hidden');}
async function login(){err('');$('adminLoginBtn').disabled=true;try{const res=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('adminPassword').value})});const d=await res.json().catch(()=>({}));if(!res.ok)throw new Error(d.error||'登录失败');token=d.token;sessionStorage.setItem('ads_admin_token',token);localStorage.setItem('ads_admin_token',token);showDash();await loadStudents();}catch(e){err(e.message);}finally{$('adminLoginBtn').disabled=false;}}
function taskLabel(id){return tasks.find(t=>t.id===id)?.label||id;}
function renderTaskControls(){const box=$('taskControlButtons');box.innerHTML='';for(const t of tasks){const b=document.createElement('button');b.className='task-control-btn'+(t.id===activeTaskId?' active':'');b.innerHTML=`<span>${t.label}</span>${t.id===activeTaskId?'<small>当前任务</small>':''}`;b.addEventListener('click',()=>switchTask(t.id));box.appendChild(b);}$('activeTaskTitle').textContent=`学生当前进入：${taskLabel(activeTaskId)}`;}
async function switchTask(taskId){if(taskId===activeTaskId)return;const label=taskLabel(taskId);if(!confirm(`确定把当前课堂任务切换为“${label}”吗？\n学生端会自动进入这个任务；原任务对话不会删除。`))return;const res=await api('/api/admin/task',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({taskId})});const d=await res.json().catch(()=>({}));if(!res.ok)throw new Error(d.error||'切换任务失败');activeTaskId=d.activeTaskId;tasks=d.tasks||tasks;selectedTaskId=activeTaskId;renderTaskControls();await loadStudents({silent:true});if(selectedKey)await loadStudent(selectedKey,selectedTaskId,{force:true});}
function totalMessages(s){return Object.values(s.taskStats||{}).reduce((n,x)=>n+Number(x?.messageCount||0),0);}
function renderStudents(){const list=$('studentList');list.innerHTML='';$('studentCount').textContent=`${students.length} 人`;if(!students.length){list.innerHTML='<div class="empty">还没有学生名单。</div>';return;}for(const s of students){const div=document.createElement('div');div.className='student-item'+(s.studentKey===selectedKey?' active':'');const title=document.createElement('div');title.className='student-title';const name=document.createElement('span');name.textContent=s.studentName+(s.isTest?'（S00）':'');title.appendChild(name);const badge=document.createElement('span');if(s.isTest){badge.className='badge test';badge.textContent='测试';}else{badge.className=`badge ${s.hasEntered?'entered':'waiting'}`;badge.textContent=s.hasEntered?'已进入':'未进入';}title.appendChild(badge);const sub=document.createElement('div');sub.className='student-sub';sub.textContent=s.hasEntered?`${totalMessages(s)} 条消息 · 最近 ${fmtTime(s.updatedAt)}`:(s.isTest?'固定测试账号':'尚无学习记录');const mini=document.createElement('div');mini.className='task-mini-stats';mini.innerHTML=tasks.map(t=>`<span class="${t.id===activeTaskId?'current':''}">${t.label} ${Number(s.taskStats?.[t.id]?.messageCount||0)}</span>`).join('');div.append(title,sub,mini);div.addEventListener('click',()=>loadStudent(s.studentKey,selectedTaskId||activeTaskId,{force:true}));list.appendChild(div);}}
async function loadStudents({silent=false}={}){const res=await api('/api/admin/students');const d=await res.json();if(!res.ok)throw new Error(d.error||'加载失败');students=d.students||[];tasks=d.tasks||tasks;activeTaskId=d.activeTaskId||activeTaskId;if(!selectedTaskId)selectedTaskId=activeTaskId;renderTaskControls();renderStudents();const updated=d.rosterUpdatedAt?` · 名单更新 ${fmtTime(d.rosterUpdatedAt)}`:'';$('rosterSummary').textContent=d.rosterCount?`正式名单 ${d.rosterCount} 人 · 已进入 ${d.enteredCount} 人${updated}`:'还没有上传正式名单；测试账号可直接使用“测试”登录。';if(!silent&&selectedKey)await loadStudent(selectedKey,selectedTaskId,{force:false});}
async function fetchProtectedImage(url){const res=await api(url);if(!res.ok)return null;const blob=await res.blob(),obj=URL.createObjectURL(blob);imageUrls.add(obj);return obj;}
function renderStudentTaskTabs(data){const box=$('studentTaskTabs');box.innerHTML='';box.classList.remove('hidden');for(const t of data.tasks||[]){const b=document.createElement('button');b.className='student-task-tab'+(t.id===selectedTaskId?' active':'')+(t.id===data.activeTask?.id?' current':'');b.innerHTML=`<span>${t.label}</span><small>${t.messageCount||0} 条${t.id===data.activeTask?.id?' · 当前':''}</small>`;b.addEventListener('click',()=>{selectedTaskId=t.id;loadStudent(selectedKey,t.id,{force:true});});box.appendChild(b);}}
async function loadStudent(studentKey,taskId,{force=false}={}){selectedKey=studentKey;selectedTaskId=taskId||activeTaskId;renderStudents();const res=await api(`/api/admin/student?studentKey=${encodeURIComponent(studentKey)}&taskId=${encodeURIComponent(selectedTaskId)}`);const d=await res.json();if(!res.ok)throw new Error(d.error||'加载学生记录失败');const p=d.profile;$('detailTitle').textContent=p.studentName+(p.isTest?'（测试账号 S00）':'');$('detailSub').textContent=p.createdAt?`首次进入 ${fmtTime(p.createdAt)} · 最近活动 ${fmtTime(p.updatedAt)}`:'该学生尚未进入平台。';selectedTaskId=d.selectedTask.id;renderStudentTaskTabs(d);const count=d.messages?.length||0;$('messageCountPill').textContent=`${d.selectedTask.label} · ${count} 条`;$('messageCountPill').classList.remove('hidden');const signature=`${studentKey}|${selectedTaskId}|${d.messages?.map(m=>`${m.messageId}:${m.createdAt}`).join(',')}`;if(!force&&signature===lastMessageSignature)return;lastMessageSignature=signature;const box=$('adminMessages');box.innerHTML='';if(!d.messages?.length){box.innerHTML=`<div class="empty empty-chat"><strong>${d.selectedTask.label}暂无对话</strong><span>该学生还没有在这个任务中提交内容。</span></div>`;return;}for(const m of d.messages){const row=document.createElement('div');row.className=`admin-chat-row ${m.role==='user'?'student':'ai'}`;const item=document.createElement('div');item.className='admin-msg';const meta=document.createElement('div');meta.className='meta';const role=document.createElement('span');role.className='role-label';role.textContent=m.role==='user'?'学生':'AI';const time=document.createElement('span');time.textContent=fmtTime(m.createdAt);meta.append(role,time);const content=document.createElement('div');content.className='content';content.textContent=m.text||'';item.append(meta,content);if(m.imageId){const loading=document.createElement('div');loading.className='muted image-loading';loading.textContent='正在加载图片…';item.appendChild(loading);fetchProtectedImage(`/api/admin/image?studentKey=${encodeURIComponent(m.sourceStudentKey||studentKey)}&taskId=${encodeURIComponent(selectedTaskId)}&imageId=${encodeURIComponent(m.imageId)}`).then(src=>{if(!src){loading.textContent='图片加载失败';return;}const img=document.createElement('img');img.src=src;img.alt='学生上传图片';loading.replaceWith(img);});}row.appendChild(item);box.appendChild(row);}box.scrollTop=box.scrollHeight;}
function openRosterModal(){pendingRoster=[];rosterErr('');$('rosterFile').value='';$('rosterFileName').textContent='点击选择 Excel 或 CSV';$('rosterPreview').classList.add('hidden');$('confirmRosterBtn').disabled=true;$('rosterModal').classList.remove('hidden');document.body.classList.add('modal-open');}
function closeRosterModal(){$('rosterModal').classList.add('hidden');document.body.classList.remove('modal-open');rosterErr('');}
function headerIndex(headers,names){const n=headers.map(v=>String(v??'').trim().toLowerCase());for(const x of names){const i=n.indexOf(x.toLowerCase());if(i>=0)return i;}return-1;}
function parseWorkbook(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('无法读取文件。'));reader.onload=()=>{try{if(!window.XLSX)throw new Error('Excel 读取组件未加载，请刷新后重试。');const wb=XLSX.read(reader.result,{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false});if(rows.length<2)throw new Error('名单至少需要表头和 1 名学生。');const ni=headerIndex(rows[0],['姓名','学生姓名','studentname','student_name','name']);if(ni<0)throw new Error('第一行必须包含“姓名”列。');const data=rows.slice(1).map(r=>({studentName:String(r[ni]??'').trim()})).filter(r=>r.studentName);const seen=new Set();for(const r of data){if(['测试','S00'].includes(r.studentName.toUpperCase()))throw new Error('“测试 / S00”是系统内置测试账号，不需要写入名单。');if(seen.has(r.studentName))throw new Error(`名单中存在重名：${r.studentName}。姓名登录无法区分，请先添加可识别标记。`);seen.add(r.studentName);}if(!data.length)throw new Error('没有读取到学生姓名。');resolve(data);}catch(e){reject(e);}};reader.readAsArrayBuffer(file);});}
function renderRosterPreview(rows){$('rosterPreview').innerHTML=`<strong>读取成功</strong><span>${rows.length} 名学生</span><small>示例：${rows.slice(0,5).map(r=>r.studentName).join('、')}${rows.length>5?'…':''}</small>`;$('rosterPreview').classList.remove('hidden');}
async function handleRosterFile(){rosterErr('');const file=$('rosterFile').files?.[0];pendingRoster=[];$('confirmRosterBtn').disabled=true;if(!file)return;$('rosterFileName').textContent=file.name;try{pendingRoster=await parseWorkbook(file);renderRosterPreview(pendingRoster);$('confirmRosterBtn').disabled=false;}catch(e){rosterErr(e.message);$('rosterPreview').classList.add('hidden');}}
async function saveRoster(){if(!pendingRoster.length)return;rosterErr('');$('confirmRosterBtn').disabled=true;try{const res=await api('/api/admin/roster',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({students:pendingRoster})});const d=await res.json().catch(()=>({}));if(!res.ok)throw new Error(d.error||'名单上传失败');closeRosterModal();await loadStudents();alert(`名单已更新，共 ${d.count} 名学生。已有任务对话不会删除。`);}catch(e){rosterErr(e.message);}finally{$('confirmRosterBtn').disabled=false;}}
function downloadTemplate(){if(!window.XLSX)return alert('Excel 组件未加载，请刷新页面后重试。');const ws=XLSX.utils.aoa_to_sheet([['姓名'],['张三'],['李四'],['王五']]);ws['!cols']=[{wch:18}];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'学生名单');XLSX.writeFile(wb,'学生名单模板.xlsx');}
async function download(path,filename){const res=await api(path);if(!res.ok){const d=await res.json().catch(()=>({}));throw new Error(d.error||'导出失败');}const blob=await res.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);}
$('adminLoginBtn').addEventListener('click',login);$('adminPassword').addEventListener('keydown',e=>{if(e.key==='Enter')login();});$('refreshBtn').addEventListener('click',()=>loadStudents().catch(e=>alert(e.message)));$('uploadRosterBtn').addEventListener('click',openRosterModal);$('downloadTemplateBtn').addEventListener('click',downloadTemplate);$('rosterModalClose').addEventListener('click',closeRosterModal);document.querySelector('[data-close-roster-modal]').addEventListener('click',closeRosterModal);$('rosterFile').addEventListener('change',handleRosterFile);$('confirmRosterBtn').addEventListener('click',saveRoster);$('exportJsonBtn').addEventListener('click',()=>download('/api/admin/export?format=json','ai-dynamic-scaffold.json').catch(e=>alert(e.message)));$('exportCsvBtn').addEventListener('click',()=>download('/api/admin/export?format=csv','ai-dynamic-scaffold.csv').catch(e=>alert(e.message)));$('logoutBtn').addEventListener('click',async()=>{try{await api('/api/admin/logout',{method:'POST'});}catch{}token='';sessionStorage.removeItem('ads_admin_token');localStorage.removeItem('ads_admin_token');showLogin();});window.addEventListener('beforeunload',()=>imageUrls.forEach(u=>URL.revokeObjectURL(u)));
setInterval(async()=>{if(!token||$('dashboard').classList.contains('hidden'))return;try{await loadStudents({silent:true});if(selectedKey)await loadStudent(selectedKey,selectedTaskId||activeTaskId,{force:false});}catch{}},5000);
(async function boot(){if(!token)return showLogin();try{showDash();await loadStudents();}catch{showLogin();}})();
