const $=id=>document.getElementById(id);
const state={studentKey:'',studentName:'',taskId:'',taskLabel:'',conversationId:'',requiresInitialImage:false,selectedFile:null,sending:false,taskPoll:null};
function fmtTime(iso){try{return new Date(iso).toLocaleString('zh-CN',{hour12:false});}catch{return'';}}
function showError(text){$('loginError').textContent=text;$('loginError').classList.toggle('hidden',!text);}
function showAdminError(text=''){$('coverAdminError').textContent=text;$('coverAdminError').classList.toggle('hidden',!text);}
function openAdminModal(){showAdminError('');$('coverAdminPassword').value='';$('adminModal').classList.remove('hidden');document.body.classList.add('modal-open');setTimeout(()=>$('coverAdminPassword').focus(),0);}
function closeAdminModal(){$('adminModal').classList.add('hidden');document.body.classList.remove('modal-open');showAdminError('');}
async function coverAdminLogin(){showAdminError('');const password=$('coverAdminPassword').value;if(!password)return showAdminError('请输入管理员密码。');$('coverAdminLoginBtn').disabled=true;try{const res=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'登录失败');sessionStorage.setItem('ads_admin_token',data.token);localStorage.setItem('ads_admin_token',data.token);location.href='/admin.html#auth='+encodeURIComponent(data.token);}catch(e){showAdminError(e.message);}finally{$('coverAdminLoginBtn').disabled=false;}}
function scrollBottom(){const el=$('messages');el.scrollTop=el.scrollHeight;}
function renderMessage(msg){$('chatEmpty')?.remove();const wrap=document.createElement('div');wrap.className=`msg ${msg.role==='user'?'user':'assistant'}`;const bubble=document.createElement('div');bubble.className='bubble';if(msg.localImageUrl){const img=document.createElement('img');img.className='msg-image';img.src=msg.localImageUrl;img.alt='上传图片';bubble.appendChild(img);}if(msg.text){const t=document.createElement('div');t.textContent=msg.text;bubble.appendChild(t);}const tm=document.createElement('span');tm.className='msg-time';tm.textContent=fmtTime(msg.createdAt||new Date().toISOString());bubble.appendChild(tm);wrap.appendChild(bubble);$('messages').appendChild(wrap);scrollBottom();}
function setTaskUi(){ $('currentTaskBadge').textContent=state.taskLabel||''; $('studentMeta').textContent=state.studentName; }
function showTaskNotice(text){const el=$('taskNotice');el.textContent=text;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),4500);}
function setProcessingUI(on){state.sending=!!on;$('processingOverlay').classList.toggle('hidden',!on);$('sendBtn').disabled=!!on;$('imageInput').disabled=!!on;$('removeImageBtn').disabled=!!on;$('switchBtn').disabled=!!on;$('messageInput').disabled=!!on||state.requiresInitialImage;$('sendBtn').textContent=on?'AI 处理中…':(state.requiresInitialImage?(state.selectedFile?'发送图片':'请先选图'):'发送');$('sendStatus').textContent=on?'AI 正在处理，请稍候…':'';if(on)scrollBottom();}
async function startStudent(studentName){const res=await fetch('/api/student/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({studentName})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'进入失败');return data;}
function applyStudentData(data,{notice=false}={}){const oldTask=state.taskId;state.studentKey=data.studentKey;state.studentName=data.studentName;state.taskId=data.taskId;state.taskLabel=data.taskLabel;state.conversationId=data.conversationId||'';state.requiresInitialImage=!!data.requiresInitialImage;setTaskUi();showChat(data.messages||[]);updateInitialImageUi();if(notice&&oldTask&&oldTask!==state.taskId)showTaskNotice(`老师已切换到${state.taskLabel}，请先上传本任务的作品图片。`);}
async function enter(){showError('');const name=$('studentName').value.trim();if(!name)return showError('请输入姓名。');$('enterBtn').disabled=true;$('enterBtn').innerHTML='正在进入…';try{applyStudentData(await startStudent(name));startTaskWatcher();}catch(e){showError(e.message);}finally{$('enterBtn').disabled=false;$('enterBtn').innerHTML='进入学习平台 <span aria-hidden="true">→</span>';}}
function showChat(history=[]){$('loginView').classList.add('hidden');$('chatView').classList.remove('hidden');setTaskUi();$('messages').innerHTML='';if(!history.length){const empty=document.createElement('div');empty.id='chatEmpty';empty.className='chat-empty';empty.innerHTML=`<div class="chat-empty-icon">▧</div><strong>${state.taskLabel}：先上传作品图片</strong><span>每个新任务都从作品图片开始。AI 回复后，可以继续发送文字或新的图片。</span>`;$('messages').appendChild(empty);}else history.forEach(m=>renderMessage({role:m.role,text:m.text,createdAt:m.createdAt}));}
function clearImage(){state.selectedFile=null;$('imageInput').value='';$('previewRow').classList.add('hidden');$('previewImage').src='';}
function updateInitialImageUi(){
  const input=$('messageInput');
  if(state.requiresInitialImage){
    input.value='';
    input.disabled=true||!!state.sending;
    input.placeholder='本任务请先上传作品图片';
    if(!state.sending) $('sendBtn').textContent=state.selectedFile?'发送图片':'请先选图';
  }else{
    input.disabled=!!state.sending;
    input.placeholder='输入内容；也可以继续上传图片';
    if(!state.sending) $('sendBtn').textContent='发送';
  }
  $('imageInput').disabled=!!state.sending;
  $('removeImageBtn').disabled=!!state.sending;
  $('switchBtn').disabled=!!state.sending;
}
async function responseError(res,fallback='请求失败'){const type=res.headers.get('content-type')||'';if(type.includes('application/json')){const d=await res.json().catch(()=>({}));const e=new Error(d.error||d.message||`${fallback}（HTTP ${res.status}）`);e.data=d;e.status=res.status;return e;}const txt=(await res.text().catch(()=>'' )).trim();return new Error(txt&&txt.length<300?`${fallback}：${txt}`:`${fallback}（HTTP ${res.status}）`);}
async function pollChatStatus({conversationId,chatId,taskId}){for(let i=0;i<120;i++){const qs=new URLSearchParams({studentKey:state.studentKey,studentName:state.studentName,taskId,conversationId,chatId});const res=await fetch(`/api/chat/status?${qs}`,{cache:'no-store'});if(!res.ok)throw await responseError(res,'读取 AI 回复失败');const data=await res.json().catch(()=>({}));if(data.status==='completed')return data;if(data.status==='failed')throw new Error(data.error||'AI 执行失败');$('sendStatus').textContent='AI 正在处理，请稍候…';await new Promise(r=>setTimeout(r,1200));}throw new Error('AI 回复时间较长，请稍后重试。');}
async function refreshToCurrentTask({notice=true}={}){if(!state.studentName||state.sending)return;const data=await startStudent(state.studentName);if(data.taskId!==state.taskId)applyStudentData(data,{notice});}
function startTaskWatcher(){clearInterval(state.taskPoll);state.taskPoll=setInterval(async()=>{try{const res=await fetch('/api/task/current',{cache:'no-store'});const data=await res.json().catch(()=>({}));if(res.ok&&data.activeTask?.id&&data.activeTask.id!==state.taskId&&!state.sending)await refreshToCurrentTask({notice:true});}catch{}},5000);}
async function sendMessage(){if(state.sending)return;const text=$('messageInput').value.trim(),file=state.selectedFile;if(state.requiresInitialImage&&!file){alert('本任务第一次提交请先上传作品图片。');return;}if(!text&&!file)return;if(file&&file.size>10*1024*1024)return alert('图片请控制在 10 MB 以内。');setProcessingUI(true);const localImageUrl=file?URL.createObjectURL(file):null;renderMessage({role:'user',text:text||'（上传了一张图片）',localImageUrl,createdAt:new Date().toISOString()});$('messageInput').value='';clearImage();const taskAtSend=state.taskId;const form=new FormData();form.append('studentKey',state.studentKey);form.append('studentName',state.studentName);form.append('taskId',taskAtSend);form.append('message',text);if(state.conversationId)form.append('conversationId',state.conversationId);if(file)form.append('image',file,file.name);try{const res=await fetch('/api/chat',{method:'POST',body:form});if(!res.ok){const e=await responseError(res,'发送失败');if(e.status===409&&e.data?.activeTask){await refreshToCurrentTask({notice:true});return;}throw e;}const data=await res.json().catch(()=>({}));state.conversationId=data.conversationId||state.conversationId;if(file){state.requiresInitialImage=false;updateInitialImageUi();}const done=await pollChatStatus({conversationId:data.conversationId,chatId:data.chatId,taskId:taskAtSend});if(state.taskId===taskAtSend)renderMessage({role:'assistant',text:done.answer||'AI 没有返回文字回复。',createdAt:done.createdAt});}catch(e){if(state.taskId===taskAtSend)renderMessage({role:'assistant',text:`本次请求失败：${e.message}`,createdAt:new Date().toISOString()});}finally{setProcessingUI(false);updateInitialImageUi();try{await refreshToCurrentTask({notice:true});}catch{}}}
$('adminEntryBtn').addEventListener('click',openAdminModal);$('adminModalClose').addEventListener('click',closeAdminModal);document.querySelector('[data-close-admin-modal]').addEventListener('click',closeAdminModal);$('coverAdminLoginBtn').addEventListener('click',coverAdminLogin);$('coverAdminPassword').addEventListener('keydown',e=>{if(e.key==='Enter')coverAdminLogin();});$('enterBtn').addEventListener('click',enter);$('studentName').addEventListener('keydown',e=>{if(e.key==='Enter')enter();});$('sendBtn').addEventListener('click',sendMessage);$('messageInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage();}});$('imageInput').addEventListener('change',()=>{const file=$('imageInput').files?.[0];if(!file){clearImage();updateInitialImageUi();return;}if(!file.type.startsWith('image/')){alert('请选择图片文件。');clearImage();updateInitialImageUi();return;}state.selectedFile=file;$('previewImage').src=URL.createObjectURL(file);$('previewName').textContent=file.name;$('previewRow').classList.remove('hidden');updateInitialImageUi();});$('removeImageBtn').addEventListener('click',()=>{clearImage();updateInitialImageUi();});$('switchBtn').addEventListener('click',()=>{clearInterval(state.taskPoll);Object.assign(state,{studentKey:'',studentName:'',taskId:'',taskLabel:'',conversationId:'',requiresInitialImage:false,selectedFile:null,sending:false,taskPoll:null});clearImage();$('chatView').classList.add('hidden');$('loginView').classList.remove('hidden');$('studentName').value='';$('messageInput').value='';});
(function boot(){clearInterval(state.taskPoll);$('chatView').classList.add('hidden');$('loginView').classList.remove('hidden');$('processingOverlay')?.classList.add('hidden');updateInitialImageUi();})();
